name: Build IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          PROJ=$(ls -d *.xcodeproj | head -n 1)
          xcodebuild build -project "$PROJ" -scheme webview -sdk iphoneos CODE_SIGNING_ALLOWED=NO -configuration Release -derivedDataPath build_data
          mkdir -p Payload
          find build_data -name "*.app" -exec cp -r {} Payload/ \;
          zip -r MyApp.ipa Payload
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Full-App-IPA
          path: MyApp.ipa
