name: Build IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          # تحديد اسم المشروع والـ Scheme تلقائياً
          PROJ=$(ls -d *.xcodeproj | head -n 1)
          SCHEME="webview" # هذا هو الاسم الافتراضي في المستودع الذي تستخدمه
          
          xcodebuild archive -project "$PROJ" -scheme "$SCHEME" -archivePath "$PWD/build/$SCHEME.xcarchive" -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO
          
          mkdir -p Payload
          cp -r build/$SCHEME.xcarchive/Products/Applications/*.app Payload/
          zip -r MyFinalApp.ipa Payload
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: App-Ready
          path: MyFinalApp.ipa
